### ISSUE TITLE
File Not Decrypted

### ISSUE THREAD

**Issue by foxethiel** [NDDDDDDDDD/mubi-downloader#11]
File and subtitles successfully download but the .mp4 cannot be opened so the file has not been decrypted, any ideas?

**Comment by NDDDDDDDDD** [comment]
hmm, could you send the log from the script?

**Comment by foxethiel** [comment]
Hopefully this is what you're looking for, I'm extremely new to Python so sorry if it's not 
[log.txt](https://github.com/NDDDDDDDDD/mubi-downloader/files/15258356/log.txt)

**Comment by NDDDDDDDDD** [comment]
yes that would be it, that looks like the output of the program. However I don't see any issues from this log, seems like its downloading the audio and video, is the download frozen on your end?

**Comment by foxethiel** [comment]
When I go to open the video nothing happens, it's just stuck trying to load. The download doesn't seem to freeze as it gets to 100% everytime.

**Comment by NDDDDDDDDD** [comment]
hmm okay, are there any errors being outputted by the python script?

**Comment by foxethiel** [comment]
There's no errors that I can see, once the download has completed it just automatically closes

**Comment by foxethiel** [comment]
Okay so I recorded the window to see if there were any errors I missed and I found something at the very end of the script
![Error](https://github.com/NDDDDDDDDD/mubi-downloader/assets/82032851/0005c86c-15b1-4cfc-a2e1-0ffc69994cc6)

**Comment by NDDDDDDDDD** [comment]
Hi, sorry for the delay in getting back to you on this.
CMD seems to have some issues running the script, I recommend using an IDE like visual studio code

**Comment by foxethiel** [comment]
I tried running the code through Visual Studio but it seemed to bring up an error before it was able to start. I'll try it again and grab a screenshot of what comes through when trying to run it.

**Comment by foxethiel** [comment]
Visual Studio Code isn't running the script either, it just keeps saying ffmepg isn't installed when it's there. I tried PyCharm just to see if anything would change but it's still not making the video available

**Comment by foxethiel** [comment]
It's in both, in the main folder where the script is running and in PATH

**Comment by free-hornet** [comment]
hi, i have the same problem

![image](https://github.com/NDDDDDDDDD/mubi-downloader/assets/107969090/263eeec5-925d-4233-894c-22423a8f4ed0)

**Comment by free-hornet** [comment]
I was able to fix it by downloading  [packager-win-x64.exe](https://github.com/shaka-project/shaka-packager/releases/tag/v3.2.0), instead of mpd_generator, renamed the file to 'packager', and changed it in the script as well. hope it works for you.

![image](https://github.com/NDDDDDDDDD/mubi-downloader/assets/107969090/02398b5a-58aa-403b-af79-d4069e570f3b)

**Comment by foxethiel** [comment]
I'll adjust the code and see if it fixes my issue as well, thanks for the input @free-hornet.

**Comment by foxethiel** [comment]
A very late update but the method works and the code is running in natively through Python!
