### ISSUE TITLE
Video has no auido file

### ISSUE THREAD

**Issue by epicturegoer3** [NDDDDDDDDD/mubi-downloader#3]
Downloaded decrypted video has no audio and external audio .m4a file has no audio also. How can i fix this issue? Thanks.

**Comment by NDDDDDDDDD** [comment]
Sorry for the late reply, which specific movie are you trying to download?

**Comment by epicturegoer3** [comment]
Everytime I tried i face the same issue. Everything is work fine but I think "Run shaka-packager to decrypt the audio file" step is not working because at the end there is no decrypted audio file and existing .m4a file has no sound.

**Comment by skyverdant** [comment]
If the language code is three letters instead of two the script will choke and will not finish decrypting the audio file. As a quick fix, you can modify the script near the bottom and change it to three letters instead of two.

**Comment by NDDDDDDDDD** [comment]
oh sorry, i wish i still could bug test and stuff but its hard to do anything without an account :/

**Comment by NDDDDDDDDD** [comment]
should work now if someone could test with the movie that was causing this issue
