### ISSUE TITLE
Suddenly unable to search for 'cenc'. 

### ISSUE THREAD

**Issue by Phosphenenene** [NDDDDDDDDD/mubi-downloader#4]
I downloaded it on July 5th, but on the 6th, I couldn't search for 'cenc' anymore.

**Comment by skyverdant** [comment]
Things seem to have changed on mubi’s end; it fails for me too.

**Comment by skyverdant** [comment]
Noticed a new parental notification thing on the view section, I wonder if that has anything to do with it.

**Comment by NDDDDDDDDD** [comment]
hmm maybe, sadly i have no MUBI account at the moment

**Comment by skyverdant** [comment]
I was wrong, my problem isn't with mubi. The problem on my end is that cdrm-project.com went down.
They said they would bring it back up tomorrow, July 14th. Time will tell, fingers crossed.
I went down some rabbit holes today trying to do CDM on my own machine. No luck yet.

**Comment by skyverdant** [comment]
Now they are saying monday.

**Comment by NDDDDDDDDD** [comment]
ah okay, would be very much appreciated if you can confirm if it works again, whenever they deliver!

**Comment by skyverdant** [comment]
still not up, I will keep checking

**Comment by kutsaltotem** [comment]
can you check again?

**Comment by NDDDDDDDDD** [comment]
This part is working, searching cenc in chromes traffic manager shows the widevine request
